# Generated by Django 3.2.7 on 2021-09-28 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('lastpubdate', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
